### ISSUE TITLE
Wie bekomme ich die Icons auf die Ulanci Awtrix geladen ?

### ISSUE THREAD

**Issue by distanzcheck** [jc-23/home-assistant#2]
Könntest Du mir bitte jemand erklären wie ich die Icons auf die Ulanci -AWTRIX hochladen muß ? Wetterwarnungen werden angezeigt, leider ohne Icons. Gruß Dirk 
Oder mir schreiben wo es genau beschireben ist,

Bekomme beim Upload diese Fehlermeldung:
![UploadFehler](https://github.com/user-attachments/assets/84a89c39-77c3-4d60-9d51-5fc208c4a847)

**Comment by jc-23** [comment]
Du hast das Paket "file" nicht installiert, daher schlägt die Überprüfung auf eine GIF-Datei fehl. Siehe die Ausgabe vor den Fehlern "[...] file: command not found". Sobald du es installiert hast, sollte es funktionieren.

**Comment by distanzcheck** [comment]
Habe es anders hinbekommen.
